//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_WPF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Children
    {
        public int ID_children { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public string Patronymic { get; set; }
        public int ID_group { get; set; }
        public string physical_1 { get; set; }
        public string physical_2 { get; set; }
        public string physical_3 { get; set; }
        public string physical_4 { get; set; }
        public string physical_5 { get; set; }
        public string physical_6 { get; set; }
        public string physical_7 { get; set; }
        public string artistic_1 { get; set; }
        public string artistic_2 { get; set; }
        public string artistic_3 { get; set; }
        public string artistic_4 { get; set; }
        public string artistic_5 { get; set; }
        public string artistic_6 { get; set; }
        public string artistic_7 { get; set; }
        public string speech_1 { get; set; }
        public string speech_2 { get; set; }
        public string speech_3 { get; set; }
        public string speech_4 { get; set; }
        public string speech_5 { get; set; }
        public string speech_6 { get; set; }
        public string speech_7 { get; set; }
        public string cognitive_1 { get; set; }
        public string cognitive_2 { get; set; }
        public string cognitive_3 { get; set; }
        public string cognitive_4 { get; set; }
        public string cognitive_5 { get; set; }
        public string cognitive_6 { get; set; }
        public string cognitive_7 { get; set; }
        public string social_1 { get; set; }
        public string social_2 { get; set; }
        public string social_3 { get; set; }
        public string social_4 { get; set; }
        public string social_5 { get; set; }
        public string social_6 { get; set; }
        public string social_7 { get; set; }
    
        public virtual Group Group { get; set; }
    }
}
